# Use the official Node.js runtime as the base image
FROM node:18

# Set the working directory inside the container
WORKDIR /app

# Copy the package.json and package-lock.json files to the working directory
COPY package*.json /app

# Install the application dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . /app

# Expose the port on which your application will run
EXPOSE 80

# Set the command to run your application
CMD ["node", "index.js"]
